"""Master ground-truth labels CSV (``master_clauses.csv``) loader.

The mailroom's curated ground-truth table (generated by llm-mailroom's
``fetch_full_cuad.py``) carries, per contract, the NORMALIZED answer for
every CUAD category: one raw label column and one ``-Answer`` column
("Document Name", "Document Name-Answer", "Parties", "Parties-Answer",
..., "Third Party Beneficiary", "Third Party Beneficiary-Answer").

The ``-Answer`` values are the canonical scalar forms used for
regression-style diagnostics — e.g. ``Effective Date-Answer = "5/8/14"``,
``Renewal Term-Answer = "2 years"``, ``Governing Law-Answer = "Nevada"``,
``Non-Compete-Answer = "Yes"/"No"``. The raw clause-label text inside
``CUAD_v1.json`` is noisier ("7th day of September, 1999."), so the master
answers are the preferred parse source for the extraction MAE diagnostics
(see ``src/metrics.py``).

Rows join to CUAD documents by filename: the CSV ``Filename`` is the
CUAD_v1.json ``title`` plus a ``.pdf`` suffix, matched case/punctuation-
insensitively (510/510 titles match).
"""

from __future__ import annotations

import csv
import os
import re
from pathlib import Path

# Default location: the repo-local copy (data/cuad/master_clauses.csv — the
# curated 510-doc ground-truth table, committed so the extraction MAE
# diagnostics are self-contained), with the sibling llm-mailroom checkout as
# fallback. Overridable via the MASTER_LABELS_CSV env var or the eval
# runners' --master-labels flag.
_SIBLING_MASTER_LABELS = Path("../llm-mailroom/data/cuad/master_clauses.csv")
_REPO_MASTER_LABELS = Path(__file__).resolve().parent.parent / "data" / "cuad" / "master_clauses.csv"


def _default_master_labels() -> Path:
    """Resolve the default master-labels CSV: env override, else the
    repo-local copy, else the sibling llm-mailroom checkout."""
    env = os.environ.get("MASTER_LABELS_CSV")
    if env:
        return Path(env)
    if _REPO_MASTER_LABELS.exists():
        return _REPO_MASTER_LABELS
    return _SIBLING_MASTER_LABELS


DEFAULT_MASTER_LABELS = _default_master_labels()


def _norm_filename(value: str) -> str:
    """Normalized join key: lowercase, strip the ``.pdf`` suffix, drop all
    non-alphanumeric characters (the CSV Filename == CUAD title + ".pdf")."""
    return re.sub(r"[^a-z0-9]+", "", str(value or "").lower().replace(".pdf", ""))


def load_master_labels(path: str | Path | None = None) -> dict[str, dict[str, str]]:
    """Load the master labels CSV into ``{normalized_filename: {category: answer}}``.

    Returns an empty dict when the file does not exist or has no rows (the
    diagnostics then degrade gracefully to the raw CUAD clause-text parsing).
    """
    path = Path(path or DEFAULT_MASTER_LABELS)
    if not path.exists():
        return {}
    out: dict[str, dict[str, str]] = {}
    with open(path, encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            filename = row.get("Filename") or ""
            key = _norm_filename(filename)
            if not key:
                continue
            answers: dict[str, str] = {}
            for category, value in row.items():
                if value in (None, ""):
                    continue
                if category.endswith("-Answer"):
                    answers[category] = str(value).strip()
                elif category.endswith("- Answer"):
                    # The CSV header carries one variant with a stray space
                    # ("Notice Period To Terminate Renewal- Answer"); normalize
                    # it to the canonical "-Answer" so that category's answer
                    # loads (endswith("-Answer") would otherwise skip it).
                    answers[category.replace("- Answer", "-Answer")] = str(value).strip()
            out[key] = answers
    return out


def master_answer(master: dict[str, dict[str, str]] | None,
                  filename: str, category: str) -> str | None:
    """The normalized master answer for one (filename, category), if any."""
    if not master:
        return None
    answer = (master.get(_norm_filename(filename)) or {}).get(f"{category}-Answer")
    return answer if answer not in (None, "") else None


def resolve_expected_value(master: dict[str, dict[str, str]] | None,
                           filename: str, category: str,
                           fallback: str) -> str:
    """Preferred expected text for a field: the master normalized answer when
    present, else the raw CUAD clause-label text (``fallback``)."""
    answer = master_answer(master, filename, category)
    return answer if answer is not None else str(fallback or "")
